### ISSUE TITLE
Problema com arquivo de áudio do exercício 21

### ISSUE THREAD

**Issue by matheusfelipeog** [Coding-in-community/exercicios-CeV#2]
**Descrição**

No [exercício 21 do mundo 1](https://github.com/Coding-in-community/exercicios-CeV/blob/main/exs/mundo_1/python/021.py) é utilizado 1 [arquivo de áudio](https://github.com/Coding-in-community/exercicios-CeV/blob/main/exs/mundo_1/python/021.mp3) para reprodução e conclusão do exercício. Esse arquivo (sem compressão) tem em torno 6 MB de tamanho, comprimido fica na faixa dos 2~3 MB (como encontra-se o único no repositório).

**O problema:**

Quando começar a adicionar a solução do mesmo exercício 21 em outras linguagens, será necessário ter esse arquivo de áudio também e, obviamente, irá ter um peso desnecessário no repositório como um todo.

**Possível solução:**

Talvez criar um diretório responsável por armazenar arquivos binários, como este de áudio, de modo a compartilha-lo entre todos as soluções em diversas linguagens. Assim, mantém somente 1 único arquivo que servirá todas as soluções e evita a repetição e peso desnecessário no repositório.

Caso tenham outras soluções, descreva ela aqui

**Comment by carlos3g** [comment]
Eu estou de acordo. nenhum outro membro discordou, então pode fazer as modificações.

**Comment by KevinAp-5** [comment]
por mim tudo okay.
