### ISSUE TITLE
[FIX] erro ortográfico | python

### ISSUE THREAD

**Issue by BearingMe** [Coding-in-community/exercicios-CeV#52]
### ex037 em python - mundo 2

![image](https://user-images.githubusercontent.com/49632633/104888057-fb176b00-594a-11eb-83e5-06e5ee3cc825.png)

há um erro na escrita de "octal", tanto na apresentação do exercício quanto na demonstração dos resultados

**Comment by matheusfelipeog** [comment]
Bem observado, farei a correção
